### ISSUE TITLE
Observations conditioned on state-action-state

### ISSUE THREAD

**Issue by mykelk** [sisl/POMDPs.jl#25] opened 2015-09-03 02:50 UTC
Right now we have P(o|a, s'). Should we allow P(o|s, a, s').

PROS: More flexible. Edward can imagine cases where this might make things easier. Of course, one can always add stuff to the state. The POMDP file format allows for P(o|s, a, s').

CONS: Maybe it will slow things down? Adds another argument. Not used often?

**Comment by ebalaban** [comment] 2015-10-31 09:01
Ok, as I mentioned, I'd like to revisit this issue and see if we can converge on something and close it. Here are some thoughts to kick off discussion:

- I did another pass through the standard POMDP references and still could not find any of them using P(o|s,a,s').

- When I implemented RockSample for DESPOT, it was natural for me to think of observations depending on s,a,s'. Here is a textual description of how observations are generated for *Check_i* actions (which is the interesting part):

   "A *Check_i* action applies the rover's long-range sensor to rock *i*, returning a noisy observation from {*Good, Bad*}. The noise is determined by the efficiency factor *eta*, which decreases exponentially as a function of Euclidean distance from the target. At *eta* = 1 the sensor always returns the correct value. At *eta* = 0, there is a 50/50 chance of returning *Good* or *Bad*. At intermediate values, these behaviors are combined linearly."

   So, to be completely accurate, in this case observations are actually conditioned on (s,a), rather than on (s,a,s') or (a,s').

- I then looked through PomdpX documentation (http://bigbird.comp.nus.edu.sg/pmwiki/farm/appl/index.php?n=Main.PomdpXDocumentation), which, as mentioned above, uses P(o|a,s'). Ironically, a version of RockSample is utilized as the running example to illustrate the format. Here is what they say about observations: "In the RockSample problem, the probability of an observation is conditional on taking an action and ending in a new state." 

   The only reason they can state that though is because in RockSample the states are modeled rather crudely (they encode just the rover position and rock types) and, therefore, **the state remains exactly the same after performing a *Check_i* action** (since the rover does not move). So, that's a bit of a sleight of hand. If we are to imagine a slightly more complex model, where rover energy is part of the state vector and *Check_i* is associated with energy use, then s' would no longer be equal s.

The fact that so many respectable sources are perfectly fine with P(o|a,s') does give me a pause. It seems, however, that a good enough case can be made that the P(o|s,a,s') definition is valid and useful. So, what are we missing here?

**Comment by zsunberg** [comment] 2015-11-01 23:55
Yeah, I think P(o|s,a,s') is the better way to go. It's my fault that we
haven't moved forward on this because I was supposed to email Dr. Kaelbling
to see if she had any reason for doing it the way she did in her paper that
many people cite. I will try to do that this afternoon.

**Comment by ebalaban** [comment] 2015-11-02 04:38
No worries, I just wanted to revive this issue and see if anyone had any new thoughts or information on it. I am very curious to hear what L. Kaelbling's views on this are (thanks for emailing her). We can then decide whether we need to reach out to others in the POMDP community as well or not.

**Comment by zsunberg** [comment] 2015-11-02 05:31
Alright, actually as I was writing the email, I found out that Dr. Kaelbling does address this in her 1998 paper [1]. In section 3.1, there is a footnote that says 

> It is possible to formulate an equivalent model in which the observation depends on the previous state instead of, or *in addition to*, the resulting state, but it complicates the exposition and adds no more expressive power; such a model could be converted into a POMDP model as described above, at the cost of expanding the state space.

This is basically the same as what we have been saying. I didn't end up emailing her because it didn't seem like there was anything worth asking after reading this. My vote (though I could be convinced otherwise) is to go with s,a,s'. In cases where we call external solvers, it should be easy to check that the observation probabilities are the same for all s and throw an error if not.

[1] Kaelbling, L., Littman, M., & Cassandra, A. (1998). Planning and acting in partially observable stochastic domains. Artificial Intelligence, 101, 99–134. Retrieved from http://www.sciencedirect.com/science/article/pii/S000437029800023X

**Comment by mykelk** [comment] 2015-11-02 05:47
I'm okay with whatever you decide here. It does feel a little goofy to do a check on all s'.

**Comment by ebalaban** [comment] 2015-11-02 05:57
I see, thanks Zach. It's a matter of preference, of course, but to me P(o|s,a,s') is adding clarity when the circumstances call for it, rather than reducing it. And anything that simplifies the state vector is a plus, as far as I am concerned. My vote is for s,a,s'. I am ok with doing a check on all s or, alternatively, supporting P(o|a,s') syntax in addition to P(o|s,a,s') (I think I am in the minority on the latter though).

**Comment by ebalaban** [comment] 2015-11-02 06:04
I'd say let's wait for @etotheipluspi to cast his vote and if he concurs, change the definition to s,a,s'.

**Comment by zsunberg** [comment] 2015-11-02 06:43
Note: The reason to only support P(o|s,a,s') rather than both is that if a solver calls to P(o|a,s'), then that solver will not work with problems that assign P(o|s,a,s'). There might be a way to get around this that I am not thinking of, though.

**Comment by ebalaban** [comment] 2015-11-02 22:54
That's a good point (I forgot that we discussed this already a couple of months ago).

**Comment by ebalaban** [comment] 2015-11-04 08:53
So, is everyone more or less comfortable with P(o|s,a,s')? If so, I can make the change in the code/docs.

**Comment by mykelk** [comment] 2015-11-04 14:57
Yes.

**Comment by zsunberg** [comment] 2015-11-04 20:30
Yeah, I think so

**Comment by ebalaban** [comment] 2015-11-05 06:55
Ok, hearing no objections, I implemented the changes with 2090af2.

**Comment by goretkin** [comment] 2015-12-26 18:12
Sorry to comment on a closed issue. Is their a belief update function for observations conditioned on s, a, s'?
I see https://github.com/sisl/POMDPToolbox.jl/blob/master/src/beliefs.jl#L94, but I think that's for (o | s', a) only.

**Comment by zsunberg** [comment] 2015-12-26 21:35
Thanks for pointing that out - it appears to be an oversight. As the interface has changed, not everything in POMDPToolbox has been kept up to date. The code in POMDPToolbox should be made compatible the s,a,s` version of observation. @etotheipluspi is that your code in POMDPToolbox?

**Comment by etotheipluspi** [comment] 2016-01-05 20:04
@goretkin sorry for the slow response. You're right this needs to be updated. Feel free to submit a pull request if you'd like, otherwise I can get to it sometime this week.

**Comment by etotheipluspi** [comment] 2016-01-05 20:21
I also realized that I missed the later part of this discussion. I would like to get everyone's thoughts on the following though. 

It seems that for a problem where the observation distribution is conditioned on both s and s', the user would be unable to use solvers that support .pomdpx and .pomdp file formats. We can make sure this is clearly documented, but this split in how the problem should be formulated bothers me quite a bit (I know this was discussed in detail earlier, sorry to bring this back from the dead). At some point, we may have a Julia implementation of SARSOP without .pomdpx files, and that may solve the problem. Are there any other ideas on how we can handle this issue without eliminating some solvers from the users arsenal?

**Comment by mykelk** [comment] 2016-01-06 05:59
I think it is okay that some solvers can't solve all problems (obviously, since some can handle continuous spaces and others not). We can indicate this in the matrix about what functions are required by the different solvers.

**Comment by etotheipluspi** [comment] 2016-01-06 16:37
I'm not sure how this can be included in the matrix. Since we only have P(o|s,a,s') available, all POMDP solvers have to use it including SARSOP. In that case, we are forced to use P(o|s,a,s') when generating the .pomdpx files. The question then becomes what is the least ugly way to do it.

One way around the mess would be to keep P(o|s,a) as well. 

Are there any other clean approaches? I'm Re-opening this issue to get everyone's thoughts.

**Comment by mykelk** [comment] 2016-01-06 16:47
If you have both functions, i.e. P(o|s,a) and P(o|s,a,s'), what is the best way to tell the solver which to use?

**Comment by etotheipluspi** [comment] 2016-01-06 17:19
I think we can require that the solver only use one of P(o|s',a) or P(o|s,a,s'). The function being used can be specified in the function table, so it will be up to the user to decide how they define their observation function.

I think all the Julia implemented solvers should use the P(o|s,a,s') format, with only SARSOP and pomdp-solve requiring the P(o|s',a) format. 

If the observation is conditioned on both s and s', then the problem is not suitable for SARSOP or pomdp-solve. However, if the observation is only conditioned on s', then the user can alias P(o|s,a,s') to P(o|s',a) and use all of the solvers.

**Comment by mykelk** [comment] 2016-01-06 17:39
Sounds good to me.

**Comment by etotheipluspi** [comment] 2016-01-07 20:47
@ebalaban @zsunberg what do you think? My proposal would be to add P(o|s',a) to the function list, so we can handle .pomdpx and .pompd files. 

@zsunberg I know you were against the idea of supporting both P(o|s',a) and P(o|s,a,s') but I think having both would make it much easier to wrap existing frameworks.

**Comment by ebalaban** [comment] 2016-01-07 21:19
Sorry for the delay with responding on this. I am ok with adding P(o|s',a) (along with a description of the current pros and cons of each format). We can also state that this is, hopefully, a temporary situation and that once versions of SARSOP (and alike) supporting P(o|s,a,s') become available, P(o|s',a) will be deprecated, then removed.

**Comment by zsunberg** [comment] 2016-01-07 21:56
Yeah, I'm warming up to the idea of having P(o|a,s') in addition to P(o|s,a,s').

There should obviously be a default implementation
```julia
@pomdp_func observation(pomdp::POMDP, state::State, action::Action, statep::State, distribution=create_observation_distribution(pomdp)) = observation(pomdp, action, statep, distribution)
```
so that s,a,s' solvers automatically support a,s' problems. To be as general as possible, solvers SHOULD use P(o|s,a,s').

As far as I can tell, the only downsides to adding (a,s') are bloat and that probably some solver-writer will someday write a solver that uses (a,s') when they could have used (s,a,s'). Now these downsides seem small compared to the angst that having only (s,a,s') has caused. So, I think we can add the extra function, and I don't think it needs to be a temporary solution as @ebalaban suggested.

Also, are you sure that the SARSOP algorithm (the algorithm itself, NOT the implementation that uses .pomdp files) cannot handle a problem defined with P(o|s,a,s')?

Btw, I think the argument order should be (a,s') not (s',a).

**Comment by ebalaban** [comment] 2016-01-08 07:38
I concur with @zsunberg on (a,s') vs (s',a) format. I suggested getting rid of P(a,s') eventually precisely to reduce fragmentation and the possibility of confusion, but it would not bother me if we decide to leave it in.

**Comment by etotheipluspi** [comment] 2016-01-08 18:08
@zsunberg SARSOP can be implemented with P(o|s,a,s'), so down the line, when we have a Julia implementation that uses P(o|s,a,s'), we can shift away from the P(o|a,s') format. 

I agree with the argument format of (a,s') as well. I was being sloppy earlier.

**Comment by etotheipluspi** [comment] 2016-01-22 06:21
Added back the P(o|a,s') observation function

**Closed by etotheipluspi** 2016-01-22 06:21 UTC
